package com.laraim237.restoX.modules.audit;

public enum AuditAction {
	// Auth
    LOGIN_SUCCESS, LOGIN_FAILED, LOGOUT,
    REGISTER, EMAIL_VERIFIED, EMAIL_VERIFICATION_RESENT,
    PASSWORD_RESET_REQUESTED, PASSWORD_RESET_CONFIRMED,
    TOKEN_REFRESHED,

    // Staff
    STAFF_CREATED, STAFF_UPDATED,
    STAFF_DEACTIVATED, STAFF_ACTIVATED, INVITE_RESENT,

    // Menu
    CATEGORY_CREATED, CATEGORY_UPDATED, CATEGORY_DELETED,
    ITEM_CREATED, ITEM_UPDATED, ITEM_DELETED,
    ITEM_AVAILABILITY_TOGGLED,
    VARIANT_CREATED, VARIANT_UPDATED, VARIANT_DELETED,

    // Restaurant
    RESTAURANT_CREATED, RESTAURANT_UPDATED
}
